import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 常量定义 (必须与 src/utils/crypto.ts 和 src/core/config/ConfigManager.ts 保持一致)
const ALGORITHM = 'aes-256-gcm';
const KDF_ALGORITHM = 'sha256';
const SALT_LENGTH = 16;
const IV_LENGTH = 12;
const KEY_LENGTH = 32;
const ITERATIONS = 100000;
const APP_SALT = Buffer.from('PixelBill_Secure_Salt_v1', 'utf-8');
const MASTER_KEY = 'PixelBill_Local_Device_Key_2024';


// 默认配置
const TARGET_CONFIG = {
  apiKey: '',
  provider: 'custom',
  baseUrl: 'https://api-inference.modelscope.cn/v1',
  model: 'deepseek-ai/DeepSeek-V3.2',
  maxTokens: 2000,
  temperature: 0.3,
  enableThinking: true
};

// 获取命令行参数中的 API Key (可选)
const argApiKey = process.argv[2];

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const ask = (query) => new Promise((resolve) => rl.question(query, resolve));

// 加密函数
function encrypt(plaintext, password) {
  const key = crypto.pbkdf2Sync(
    password, 
    APP_SALT, 
    ITERATIONS, 
    KEY_LENGTH, 
    KDF_ALGORITHM
  );

  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  
  let encrypted = cipher.update(plaintext, 'utf8');
  encrypted = Buffer.concat([encrypted, cipher.final()]);
  const authTag = cipher.getAuthTag();

  // 拼接: IV + Ciphertext + AuthTag
  const combined = Buffer.concat([iv, encrypted, authTag]);
  return combined.toString('base64');
}

async function main() {
  try {
    console.log('\n=== PixelBill 安全配置生成工具 ===\n');

    let apiKey = argApiKey;
    if (!apiKey) {
      apiKey = await ask('请输入 API Key: ');
    }

    if (!apiKey || apiKey.trim() === '') {
      console.error('错误: API Key 不能为空。');
      process.exit(1);
    }

    // 允许用户覆盖默认模型配置
    const useDefaultModel = await ask(`\n使用默认模型配置? (Y/n)\n默认: ${TARGET_CONFIG.provider} / ${TARGET_CONFIG.model}\n> `);
    
    if (useDefaultModel.toLowerCase() === 'n') {
      TARGET_CONFIG.baseUrl = await ask(`Base URL [${TARGET_CONFIG.baseUrl}]: `) || TARGET_CONFIG.baseUrl;
      TARGET_CONFIG.model = await ask(`Model Name [${TARGET_CONFIG.model}]: `) || TARGET_CONFIG.model;
      const enableThinking = await ask(`Enable Thinking (Y/n) [Y]: `);
      TARGET_CONFIG.enableThinking = enableThinking.toLowerCase() !== 'n';
    }

    TARGET_CONFIG.apiKey = apiKey.trim();

    console.log('\n正在生成加密配置...');
    const jsonStr = JSON.stringify(TARGET_CONFIG);
    const encryptedBase64 = encrypt(jsonStr, MASTER_KEY);
    
    // 1. 写入 public/secure_config.json (Web 模式)
    const publicDir = path.join(__dirname, '../public');
    const publicPath = path.join(publicDir, 'secure_config.json');
    
    const publicData = {
      encryptedData: encryptedBase64,
      _note: "This file contains encrypted config generated by scripts/setup_config.js"
    };
    
    if (!fs.existsSync(publicDir)) {
      fs.mkdirSync(publicDir, { recursive: true });
    }
    
    fs.writeFileSync(publicPath, JSON.stringify(publicData, null, 2));

    // 2. 写入 virtual_android_filesys/sandbox_path/secure_config.bin (Mock Native 模式)
    const sandboxDir = path.join(__dirname, '../virtual_android_filesys/sandbox_path');
    const sandboxPath = path.join(sandboxDir, 'secure_config.bin');

    if (!fs.existsSync(sandboxDir)) {
      fs.mkdirSync(sandboxDir, { recursive: true });
    }

    fs.writeFileSync(sandboxPath, encryptedBase64, 'utf8');
    
    console.log('\n=== 配置已成功写入硬盘 ===');
    console.log(`[Web/Public] 路径: ${publicPath}`);
    console.log(`[Native/Mock] 路径: ${sandboxPath}`);
    console.log('\n验证方法:');
    console.log('1. 确保 App 正在运行 (npm run dev)');
    console.log('2. 刷新浏览器页面');
    console.log('3. App 启动时 ConfigManager 会自动读取并解密该文件');
    
    rl.close();
  } catch (e) {
    console.error('配置生成失败:', e);
    rl.close();
  }
}

main();
